# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Copy requirements file and install dependencies
COPY python-pubmed-requirements.txt ./
RUN pip install --no-cache-dir -r python-pubmed-requirements.txt

# Copy all source files
COPY . .

CMD ["python", "python-pubmed-mcp-enhanced.py"]
